name = "The Yorha Pact"
author = "LTN_Akagi"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7ff6bbb5f45dc6ef54f6f8bcd5b1119b44b278fd80fe133afc5e81410158c94"

[versions]
forge = "43.2.12"
minecraft = "1.19.2"
