name = "The Yorha Pact"
author = "LTN_Akagi"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0eead8feb1deb4f33d6ad301e4d6668779e862b82c688e7adb92b7837449f680"

[versions]
forge = "43.2.12"
minecraft = "1.19.2"
