name = "The Yorha Pact"
author = "LTN_Akagi"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9948b8216ea95a8ddebf048b8567087898d89df4ca0e1b850300ea606ed81963"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
